export const COURSES = [
  {
    id: 1,
    name: 'MS-Office',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master Microsoft Office Suite including Word, Excel, PowerPoint, and Outlook. Essential skills for any professional environment.',
    duration: '3 months',
    fee: '₹3,000',
    monthlyFee: '₹1,000',
    features: [
      'Word Processing',
      'Spreadsheets',
      'Presentations',
      'Email Management',
    ],
    category: ['Office', 'Technology'],
    searchKeys: [
      'Office',
      'MS Office',
      'Excel',
      'Word',
      'PowerPoint',
      'Outlook',
      'Basic Computer',
    ],
  },
  {
    id: 2,
    name: 'Tally Prime (GST) with Accounting',
    logo: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Learn complete accounting with Tally Prime including GST compliance, inventory management, and financial reporting.',
    duration: '3 months',
    fee: '₹4,500',
    monthlyFee: '₹1,500',
    features: [
      'GST Compliance',
      'Inventory Management',
      'Financial Reports',
      'Tax Filing',
    ],
    category: ['Accounting'],
    searchKeys: [
      'Accounting',
      'Tally',
      'Tally Prime',
      'GST',
      'Balance Sheet',
      'Taxation',
    ],
  },
  {
    id: 3,
    name: 'Adobe Photoshop',
    logo: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master photo editing, digital art, and graphic design with Adobe Photoshop. Create stunning visuals and manipulate images professionally.',
    duration: '5 weeks',
    fee: '₹2,500',
    features: [
      'Photo Editing',
      'Digital Art',
      'Layer Management',
      'Color Correction',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'Photoshop',
      'Photo Editing',
      'Graphic Design',
      'Image Processing',
    ],
  },
  {
    id: 4,
    name: 'Adobe CorelDraw',
    logo: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Learn vector graphics design with CorelDraw. Create logos, illustrations, and professional graphics for print and digital media.',
    duration: '5 weeks',
    fee: '₹2,500',
    features: [
      'Vector Graphics',
      'Logo Design',
      'Illustrations',
      'Print Design',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'CorelDraw',
      'Vector Graphics',
      'Logo Design',
      'Graphic Design',
    ],
  },
  {
    id: 5,
    name: 'Adobe Illustrator',
    logo: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master vector illustration and graphic design with Adobe Illustrator. Create scalable graphics, logos, and artwork.',
    duration: '5 weeks',
    fee: '₹2,500',
    features: [
      'Vector Illustration',
      'Logo Creation',
      'Typography',
      'Brand Design',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'Illustrator',
      'Vector Graphics',
      'Logo Design',
      'Graphic Design',
    ],
  },
  {
    id: 6,
    name: 'Adobe InDesign',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Learn professional page layout and desktop publishing with Adobe InDesign. Design magazines, brochures, and books.',
    duration: '1 month',
    fee: '₹2,500',
    features: [
      'Page Layout',
      'Typography',
      'Print Design',
      'Digital Publishing',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'InDesign',
      'Page Layout',
      'Publishing',
      'Brochure Design',
    ],
  },
  {
    id: 7,
    name: 'Advanced Excel with AI & ChatGPT',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master advanced Excel functions, data analysis, and integrate AI tools like ChatGPT for enhanced productivity and automation.',
    duration: '2 months',
    fee: '₹3,600',
    monthlyFee: '₹1,800',
    features: [
      'Advanced Formulas',
      'Data Analysis',
      'AI Integration',
      'Automation',
    ],
    category: ['Technology'],
    searchKeys: [
      'Excel',
      'Advanced Excel',
      'Data Analysis',
      'AI',
      'ChatGPT',
      'Automation',
    ],
  },
  {
    id: 8,
    name: 'Hindi & English Typing',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Improve your typing speed and accuracy in both Hindi and English. Essential skill for data entry and office work.',
    duration: '4 months',
    fee: '₹3,200',
    monthlyFee: '₹800',
    features: [
      'Speed Building',
      'Accuracy Training',
      'Bilingual Typing',
      'Practice Tests',
    ],
    category: ['Office'],
    searchKeys: [
      'Typing',
      'Hindi Typing',
      'English Typing',
      'Data Entry',
      'Typing Speed',
    ],
  },
  {
    id: 9,
    name: 'AutoCAD 2D & 3D',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn computer-aided design with AutoCAD. Create precise 2D drawings and 3D models for engineering and architecture.',
    duration: '2 months',
    fee: '₹5,000',
    monthlyFee: '₹2,500',
    features: [
      '2D Drafting',
      '3D Modeling',
      'Technical Drawing',
      'Engineering Design',
    ],
    category: ['Engineering'],
    searchKeys: [
      'Engineering',
      'AutoCAD',
      '2D Design',
      '3D Design',
      'Drafting',
    ],
  },
  {
    id: 10,
    name: 'C & C++ Programming',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Master the fundamentals of programming with C and C++. Build strong foundation for software development and system programming.',
    duration: '4 months',
    fee: '₹7,200',
    monthlyFee: '₹1,800',
    features: [
      'Programming Basics',
      'Data Structures',
      'Object-Oriented Programming',
      'System Programming',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'C Language',
      'C++',
      'Coding',
      'Software Development',
    ],
  },
  {
    id: 11,
    name: 'Java Programming',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn Java programming from basics to advanced concepts. Build enterprise applications and understand object-oriented programming.',
    duration: '2 months',
    fee: '₹5,000',
    monthlyFee: '₹2,500',
    features: [
      'OOP Concepts',
      'Enterprise Development',
      'Spring Framework',
      'Database Integration',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'Java',
      'OOPs',
      'Web Development',
      'Software Development',
    ],
  },
  {
    id: 12,
    name: 'Python Programming',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Master Python programming for web development, data analysis, and automation. One of the most versatile programming languages.',
    duration: '2 months',
    fee: '₹5,000',
    monthlyFee: '₹2,500',
    features: [
      'Web Development',
      'Data Analysis',
      'Automation',
      'Machine Learning Basics',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'Python',
      'Data Science',
      'Automation',
      'Coding',
    ],
  },
  {
    id: 13,
    name: 'Advanced Internet',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop&crop=center',
    description:
      'Master advanced internet technologies, web services, cloud computing, and digital communication tools for modern business.',
    duration: '1 month',
    fee: '₹2,500',
    monthlyFee: '₹2,500',
    features: [
      'Web Technologies',
      'Cloud Services',
      'Digital Communication',
      'Online Security',
    ],
    category: ['Technology'],
    searchKeys: [
      'Technology',
      'Internet',
      'Email',
      'Browser',
      'Net Banking',
      'Cyber Security',
    ],
  },
  {
    id: 14,
    name: 'Video Editing',
    logo: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn professional video editing techniques using industry-standard software. Create engaging content for social media and marketing.',
    duration: '1 month',
    fee: '₹2,500',
    monthlyFee: '₹2,500',
    features: [
      'Video Editing',
      'Color Grading',
      'Audio Editing',
      'Motion Graphics',
    ],
    category: ['Media'],
    searchKeys: [
      'Media',
      'Video Editing',
      'Premiere Pro',
      'After Effects',
      'YouTube',
      'Content Creation',
    ],
  },
  {
    id: 15,
    name: 'Data Analytics',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn data analysis, visualization, and business intelligence. Work with real datasets and make data-driven decisions.',
    duration: '4 months',
    fee: '₹7,200',
    monthlyFee: '₹1,800',
    features: [
      'Data Analysis',
      'Visualization',
      'Statistical Analysis',
      'Business Intelligence',
    ],
    category: ['Analytics'],
    searchKeys: [
      'Analytics',
      'Data Analysis',
      'SQL',
      'Tableau',
      'Power BI',
      'Statistics',
    ],
  },
  {
    id: 16,
    name: 'SAP Course',
    logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=100&h=100&fit=crop&crop=center',
    description:
      'Master SAP enterprise software for business process management. High-demand skill for corporate environments.',
    duration: '2 months',
    fee: '₹14,000',
    monthlyFee: '₹7,000',
    features: [
      'ERP Systems',
      'Business Processes',
      'SAP Modules',
      'Enterprise Solutions',
    ],
    category: ['Enterprise'],
    searchKeys: ['Enterprise', 'SAP', 'ERP', 'Business Process', 'Management'],
  },
  {
    id: 17,
    name: 'Web Development',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Master modern web development with HTML, CSS, JavaScript, and frameworks. Build responsive websites and web applications.',
    duration: '6 months',
    fee: '₹10,800',
    monthlyFee: '₹1,800',
    features: [
      'HTML/CSS',
      'JavaScript',
      'React/Angular',
      'Backend Development',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'Web Development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Frontend',
      'Backend',
    ],
  },
  {
    id: 18,
    name: 'Revit',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn Building Information Modeling (BIM) with Autodesk Revit. Design and document building projects with precision.',
    duration: '2 months',
    fee: '₹10,000',
    monthlyFee: '₹5,000',
    features: [
      'BIM Modeling',
      'Architectural Design',
      'MEP Systems',
      'Project Documentation',
    ],
    category: ['Architecture'],
    searchKeys: [
      'Architecture',
      'Revit',
      'BIM',
      '3D Modeling',
      'Building Design',
    ],
  },
  {
    id: 19,
    name: 'NX-CAD',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center',
    description:
      'Master advanced CAD design with Siemens NX. Professional 3D modeling and simulation for engineering applications.',
    duration: '2 months',
    fee: '₹10,000',
    monthlyFee: '₹5,000',
    features: [
      '3D Modeling',
      'Simulation',
      'Engineering Design',
      'Manufacturing',
    ],
    category: ['Engineering'],
    searchKeys: [
      'Engineering',
      'NX-CAD',
      'Siemens NX',
      'Mechanical Design',
      'Computer Aided Design',
    ],
  },
  {
    id: 20,
    name: 'Stenography Course',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn shorthand writing and stenography for court reporting, secretarial work, and fast note-taking in professional settings.',
    duration: '3 months',
    fee: '₹5,400',
    monthlyFee: '₹1,800',
    features: [
      'Shorthand Writing',
      'Speed Building',
      'Court Reporting',
      'Professional Documentation',
    ],
    category: ['Office'],
    searchKeys: [
      'Office',
      'Stenography',
      'Shorthand',
      'Court Reporter',
      'Secretarial',
    ],
  },
  {
    id: 21,
    name: 'Spoken English',
    logo: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&h=100&fit=crop&crop=center',
    description:
      'Improve your English speaking skills, pronunciation, and confidence. Essential for career growth and communication.',
    duration: '3 months',
    fee: '₹4,500',
    monthlyFee: '₹1,500',
    features: [
      'Speaking Practice',
      'Pronunciation',
      'Grammar',
      'Confidence Building',
    ],
    category: ['Language'],
    searchKeys: [
      'Language',
      'English',
      'Communication Skills',
      'Grammar',
      'Personality Development',
    ],
  },
  {
    id: 22,
    name: 'Computer Hardware',
    logo: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn computer hardware assembly, troubleshooting, and maintenance. Understand components and repair techniques.',
    duration: '3 months',
    fee: '₹18,000',
    monthlyFee: '₹6,000',
    features: [
      'Hardware Assembly',
      'Troubleshooting',
      'Component Knowledge',
      'Repair Techniques',
    ],
    category: ['Hardware'],
    searchKeys: [
      'Hardware',
      'Computer Repair',
      'PC Maintenance',
      'Networking',
      'Assembly',
    ],
  },
  {
    id: 23,
    name: 'Learn AI',
    logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master Artificial Intelligence and Machine Learning. Learn to build AI models, work with Generative AI tools, and understand the future of technology.',
    duration: '1 months',
    fee: '₹6,000',
    monthlyFee: '₹6,000',
    features: [
      'Machine Learning',
      'Neural Networks',
      'Generative AI',
      'AI Ethics',
    ],
    category: ['AI'],
    searchKeys: [
      'AI',
      'Artificial Intelligence',
      'Machine Learning',
      'Generative AI',
      'Deep Learning',
      'Neural Networks',
    ],
  },
];
