export const COURSES = [
  {
    id: 1,
    slug: 'ms-office',
    name: 'MS-Office',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master Microsoft Office Suite including Word, Excel, PowerPoint, and Outlook. Essential skills for any professional environment.',
    overview:
      'This comprehensive MS Office course at Gyanplanet Institute is meticulously designed to transform you from a basic computer user into a highly proficient professional. In today’s competitive job market, mastery of the Microsoft Office Suite is essential for any administrative or data-driven role. Throughout this three-month program, you will dive deep into Word for professional documentation, Excel for advanced data analysis and formulas, and PowerPoint for impactful visual storytelling. We also cover Outlook for efficient communication and time management. By the end of this course, you will possess the technical expertise to automate routine tasks, organize information logically, and contribute significantly to any professional environment. Gain the confidence to handle complex office tasks with ease and efficiency.',
    benefits: [
      'Increased workplace productivity',
      'Better data organization and analysis skills',
      'Professional document and report creation',
      'Enhanced career prospects in any industry',
      'Mastery of essential office automation',
    ],
    whoShouldEnroll:
      'Students, Job Seekers, Working Professionals, Data Entry Operators, and anyone looking to improve their computer literacy.',
    duration: '3 months',
    fee: '₹3,000',
    monthlyFee: '₹1,000',
    features: [
      'Word Processing',
      'Spreadsheets',
      'Presentations',
      'Email Management',
    ],
    syllabus: [
      {
        module: 'Microsoft Word',
        topics: [
          'Interface & Basic Formatting',
          'Styles & Templates',
          'Tables & Images',
          'Mail Merge',
          'Page Layout & Printing',
        ],
      },
      {
        module: 'Microsoft Excel',
        topics: [
          'Cell Referencing & Basic Formulas',
          'Data Sorting & Filtering',
          'PivotTables & Charts',
          'VLOOKUP & HLOOKUP',
          'Conditional Formatting',
        ],
      },
      {
        module: 'Microsoft PowerPoint',
        topics: [
          'Slide Design & Layouts',
          'Transitions & Animations',
          'SmartArt & Multimedia',
          'Presenting Tips',
        ],
      },
    ],
    careerOpportunities: [
      'Administrative Assistant',
      'Data Entry Operator',
      'Back Office Executive',
      'Office Coordinator',
      'Customer Support Executive',
    ],
    resources: {
      free: ['GCFGlobal Free Tutorials', 'Microsoft Support Templates'],
      paid: ['Microsoft 365 Personal', 'Advance Excel Certification'],
      online: ['Excel Online (Free)', 'Word for Web'],
      offline: ['Physical Practice Workbook'],
    },
    installationGuide:
      '1. Download the Office Setup from the official Microsoft portal.\n2. Run the installer and sign in with your Microsoft account.\n3. Follow the on-screen instructions to complete the setup.',
    alternatives: [
      { name: 'LibreOffice (Free)', link: 'https://www.libreoffice.org/' },
      { name: 'Google Workspace', link: 'https://workspace.google.com/' },
    ],
    category: ['Office', 'Technology'],
    searchKeys: [
      'Office',
      'MS Office',
      'Excel',
      'Word',
      'PowerPoint',
      'Outlook',
      'Basic Computer',
    ],
  },
  {
    id: 2,
    slug: 'tally-prime',
    name: 'Tally Prime (GST) with Accounting',
    logo: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Learn complete accounting with Tally Prime including GST compliance, inventory management, and financial reporting.',
    overview:
      'Step into the world of professional accounting with our Tally Prime (GST) with Accounting course at Gyanplanet Institute. As the industry standard for Indian businesses, Tally Prime is essential for anyone pursuing a career in finance. This course bridges the gap between theoretical accounting and practical industry requirements. You will master the fundamentals of accounting before transitioning into practical Tally operations, including ledger management, inventory tracking, and bank reconciliation. A major focus is placed on GST compliance, where you will learn to handle tax calculations and generate reports like GSTR-1 and GSTR-3B with accuracy. Whether you are a graduate or a business owner, this course provides the software expertise and tax knowledge needed to navigate the financial professional landscape confidently.',
    benefits: [
      'Master GST compliance and filing',
      'Expertise in inventory management',
      'Ability to generate accurate financial reports',
      'Understanding of banking and payroll in Tally',
      'Direct job readiness for accounting roles',
    ],
    whoShouldEnroll:
      'Commerce Graduates, Accountants, Business Owners, and professionals aiming for a career in finance or auditing.',
    duration: '3 months',
    fee: '₹4,500',
    monthlyFee: '₹1,500',
    features: [
      'GST Compliance',
      'Inventory Management',
      'Financial Reports',
      'Tax Filing',
    ],
    syllabus: [
      {
        module: 'Accounting Fundamentals',
        topics: [
          'Golden Rules of Accounting',
          'Double Entry System',
          'Ledger & Groups',
        ],
      },
      {
        module: 'Tally Essentials',
        topics: [
          'Company Creation',
          'Voucher Entry (Purchase/Sales)',
          'Bank Reconciliation',
        ],
      },
      {
        module: 'GST & Taxation',
        topics: [
          'GST Ledger Setup',
          'GSTR-1 & GSTR-3B Internal Reports',
          'TDS & TCS Basics',
        ],
      },
      {
        module: 'Inventory & Payroll',
        topics: [
          'Stock Items & Godowns',
          'Cost Centers',
          'Employee Payroll Management',
        ],
      },
    ],
    careerOpportunities: [
      'Accounts Assistant',
      'Junior Accountant',
      'GST Consultant',
      'Tally Operator',
      'Inventory Manager',
    ],
    resources: {
      free: ['Tally Solutions Official Guide', 'GST Portal Tutorials'],
      paid: ['Tally Prime License', 'Advanced GST Masterclass'],
      online: ['Tally Online Support', 'YouTube Live Classes'],
      offline: ['Tally Practice Sets'],
    },
    installationGuide:
      '1. Download Tally Prime from TallySolutions.com.\n2. Install the setup and choose Educational Mode for practice.\n3. Create your first company to start practice.',
    alternatives: [
      { name: 'Zoho Books', link: 'https://www.zoho.com/in/books/' },
      { name: 'Busy Accounting', link: 'https://busy.in/' },
    ],
    category: ['Accounting'],
    searchKeys: [
      'Accounting',
      'Tally',
      'Tally Prime',
      'GST',
      'Balance Sheet',
      'Taxation',
    ],
  },
  {
    id: 3,
    slug: 'adobe-photoshop',
    name: 'Adobe Photoshop',
    logo: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master photo editing, digital art, and graphic design with Adobe Photoshop. Create stunning visuals and manipulate images professionally.',
    duration: '5 weeks',
    fee: '₹2,500',
    features: [
      'Photo Editing',
      'Digital Art',
      'Layer Management',
      'Color Correction',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'Photoshop',
      'Photo Editing',
      'Graphic Design',
      'Image Processing',
    ],
  },
  {
    id: 4,
    slug: 'adobe-coreldraw',
    name: 'Adobe CorelDraw',
    logo: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Learn vector graphics design with CorelDraw. Create logos, illustrations, and professional graphics for print and digital media.',
    duration: '5 weeks',
    fee: '₹2,500',
    features: [
      'Vector Graphics',
      'Logo Design',
      'Illustrations',
      'Print Design',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'CorelDraw',
      'Vector Graphics',
      'Logo Design',
      'Graphic Design',
    ],
  },
  {
    id: 5,
    slug: 'adobe-illustrator',
    name: 'Adobe Illustrator',
    logo: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master vector illustration and graphic design with Adobe Illustrator. Create scalable graphics, logos, and artwork.',
    duration: '5 weeks',
    fee: '₹2,500',
    features: [
      'Vector Illustration',
      'Logo Creation',
      'Typography',
      'Brand Design',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'Illustrator',
      'Vector Graphics',
      'Logo Design',
      'Graphic Design',
    ],
  },
  {
    id: 6,
    slug: 'adobe-indesign',
    name: 'Adobe InDesign',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Learn professional page layout and desktop publishing with Adobe InDesign. Design magazines, brochures, and books.',
    duration: '1 month',
    fee: '₹2,500',
    features: [
      'Page Layout',
      'Typography',
      'Print Design',
      'Digital Publishing',
    ],
    category: ['Design'],
    searchKeys: [
      'Design',
      'InDesign',
      'Page Layout',
      'Publishing',
      'Brochure Design',
    ],
  },
  {
    id: 7,
    slug: 'advanced-excel',
    name: 'Advanced Excel with AI & ChatGPT',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master advanced Excel functions, data analysis, and integrate AI tools like ChatGPT for enhanced productivity and automation.',
    duration: '2 months',
    fee: '₹3,600',
    monthlyFee: '₹1,800',
    features: [
      'Advanced Formulas',
      'Data Analysis',
      'AI Integration',
      'Automation',
    ],
    category: ['Technology'],
    searchKeys: [
      'Excel',
      'Advanced Excel',
      'Data Analysis',
      'AI',
      'ChatGPT',
      'Automation',
    ],
  },
  {
    id: 8,
    slug: 'hindi-english-typing',
    name: 'Hindi & English Typing',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Improve your typing speed and accuracy in both Hindi and English. Essential skill for data entry and office work.',
    duration: '4 months',
    fee: '₹3,200',
    monthlyFee: '₹800',
    features: [
      'Speed Building',
      'Accuracy Training',
      'Bilingual Typing',
      'Practice Tests',
    ],
    category: ['Office'],
    searchKeys: [
      'Typing',
      'Hindi Typing',
      'English Typing',
      'Data Entry',
      'Typing Speed',
    ],
  },
  {
    id: 9,
    slug: 'autocad-2d-3d',
    name: 'AutoCAD 2D & 3D',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn computer-aided design with AutoCAD. Create precise 2D drawings and 3D models for engineering and architecture.',
    duration: '2 months',
    fee: '₹5,000',
    monthlyFee: '₹2,500',
    features: [
      '2D Drafting',
      '3D Modeling',
      'Technical Drawing',
      'Engineering Design',
    ],
    category: ['Engineering'],
    searchKeys: [
      'Engineering',
      'AutoCAD',
      '2D Design',
      '3D Design',
      'Drafting',
    ],
  },
  {
    id: 10,
    slug: 'c-cpp-programming',
    name: 'C & C++ Programming',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Master the fundamentals of programming with C and C++. Build strong foundation for software development and system programming.',
    duration: '4 months',
    fee: '₹7,200',
    monthlyFee: '₹1,800',
    features: [
      'Programming Basics',
      'Data Structures',
      'Object-Oriented Programming',
      'System Programming',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'C Language',
      'C++',
      'Coding',
      'Software Development',
    ],
  },
  {
    id: 11,
    slug: 'java-programming',
    name: 'Java Programming',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn Java programming from basics to advanced concepts. Build enterprise applications and understand object-oriented programming.',
    duration: '2 months',
    fee: '₹5,000',
    monthlyFee: '₹2,500',
    features: [
      'OOP Concepts',
      'Enterprise Development',
      'Spring Framework',
      'Database Integration',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'Java',
      'OOPs',
      'Web Development',
      'Software Development',
    ],
  },
  {
    id: 12,
    slug: 'python-programming',
    name: 'Python Programming',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Master Python programming for web development, data analysis, and automation. One of the most versatile programming languages.',
    duration: '2 months',
    fee: '₹5,000',
    monthlyFee: '₹2,500',
    features: [
      'Web Development',
      'Data Analysis',
      'Automation',
      'Machine Learning Basics',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'Python',
      'Data Science',
      'Automation',
      'Coding',
    ],
  },
  {
    id: 13,
    slug: 'advanced-internet',
    name: 'Advanced Internet',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop&crop=center',
    description:
      'Master advanced internet technologies, web services, cloud computing, and digital communication tools for modern business.',
    duration: '1 month',
    fee: '₹2,500',
    monthlyFee: '₹2,500',
    features: [
      'Web Technologies',
      'Cloud Services',
      'Digital Communication',
      'Online Security',
    ],
    category: ['Technology'],
    searchKeys: [
      'Technology',
      'Internet',
      'Email',
      'Browser',
      'Net Banking',
      'Cyber Security',
    ],
  },
  {
    id: 14,
    slug: 'video-editing',
    name: 'Video Editing',
    logo: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn professional video editing techniques using industry-standard software. Create engaging content for social media and marketing.',
    duration: '1 month',
    fee: '₹2,500',
    monthlyFee: '₹2,500',
    features: [
      'Video Editing',
      'Color Grading',
      'Audio Editing',
      'Motion Graphics',
    ],
    category: ['Media'],
    searchKeys: [
      'Media',
      'Video Editing',
      'Premiere Pro',
      'After Effects',
      'YouTube',
      'Content Creation',
    ],
  },
  {
    id: 15,
    slug: 'data-analytics',
    name: 'Data Analytics',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn data analysis, visualization, and business intelligence. Work with real datasets and make data-driven decisions.',
    duration: '4 months',
    fee: '₹7,200',
    monthlyFee: '₹1,800',
    features: [
      'Data Analysis',
      'Visualization',
      'Statistical Analysis',
      'Business Intelligence',
    ],
    category: ['Analytics'],
    searchKeys: [
      'Analytics',
      'Data Analysis',
      'SQL',
      'Tableau',
      'Power BI',
      'Statistics',
    ],
  },
  {
    id: 16,
    slug: 'sap-course',
    name: 'SAP Course',
    logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=100&h=100&fit=crop&crop=center',
    description:
      'Master SAP enterprise software for business process management. High-demand skill for corporate environments.',
    duration: '2 months',
    fee: '₹14,000',
    monthlyFee: '₹7,000',
    features: [
      'ERP Systems',
      'Business Processes',
      'SAP Modules',
      'Enterprise Solutions',
    ],
    category: ['Enterprise'],
    searchKeys: ['Enterprise', 'SAP', 'ERP', 'Business Process', 'Management'],
  },
  {
    id: 17,
    slug: 'web-development',
    name: 'Web Development',
    logo: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center',
    description:
      'Master modern web development with HTML, CSS, JavaScript, and frameworks. Build responsive websites and web applications.',
    duration: '6 months',
    fee: '₹10,800',
    monthlyFee: '₹1,800',
    features: [
      'HTML/CSS',
      'JavaScript',
      'React/Angular',
      'Backend Development',
    ],
    category: ['Programming'],
    searchKeys: [
      'Programming',
      'Web Development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Frontend',
      'Backend',
    ],
  },
  {
    id: 18,
    slug: 'revit',
    name: 'Revit',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn Building Information Modeling (BIM) with Autodesk Revit. Design and document building projects with precision.',
    duration: '2 months',
    fee: '₹10,000',
    monthlyFee: '₹5,000',
    features: [
      'BIM Modeling',
      'Architectural Design',
      'MEP Systems',
      'Project Documentation',
    ],
    category: ['Architecture'],
    searchKeys: [
      'Architecture',
      'Revit',
      'BIM',
      '3D Modeling',
      'Building Design',
    ],
  },
  {
    id: 19,
    slug: 'nx-cad',
    name: 'NX-CAD',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center',
    description:
      'Master advanced CAD design with Siemens NX. Professional 3D modeling and simulation for engineering applications.',
    duration: '2 months',
    fee: '₹10,000',
    monthlyFee: '₹5,000',
    features: [
      '3D Modeling',
      'Simulation',
      'Engineering Design',
      'Manufacturing',
    ],
    category: ['Engineering'],
    searchKeys: [
      'Engineering',
      'NX-CAD',
      'Siemens NX',
      'Mechanical Design',
      'Computer Aided Design',
    ],
  },
  {
    id: 20,
    slug: 'stenography-course',
    name: 'Stenography Course',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn shorthand writing and stenography for court reporting, secretarial work, and fast note-taking in professional settings.',
    duration: '3 months',
    fee: '₹5,400',
    monthlyFee: '₹1,800',
    features: [
      'Shorthand Writing',
      'Speed Building',
      'Court Reporting',
      'Professional Documentation',
    ],
    category: ['Office'],
    searchKeys: [
      'Office',
      'Stenography',
      'Shorthand',
      'Court Reporter',
      'Secretarial',
    ],
  },
  {
    id: 21,
    slug: 'spoken-english',
    name: 'Spoken English',
    logo: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&h=100&fit=crop&crop=center',
    description:
      'Improve your English speaking skills, pronunciation, and confidence. Essential for career growth and communication.',
    duration: '3 months',
    fee: '₹4,500',
    monthlyFee: '₹1,500',
    features: [
      'Speaking Practice',
      'Pronunciation',
      'Grammar',
      'Confidence Building',
    ],
    category: ['Language'],
    searchKeys: [
      'Language',
      'English',
      'Communication Skills',
      'Grammar',
      'Personality Development',
    ],
  },
  {
    id: 22,
    slug: 'computer-hardware',
    name: 'Computer Hardware',
    logo: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=100&h=100&fit=crop&crop=center',
    description:
      'Learn computer hardware assembly, troubleshooting, and maintenance. Understand components and repair techniques.',
    duration: '3 months',
    fee: '₹18,000',
    monthlyFee: '₹6,000',
    features: [
      'Hardware Assembly',
      'Troubleshooting',
      'Component Knowledge',
      'Repair Techniques',
    ],
    category: ['Hardware'],
    searchKeys: [
      'Hardware',
      'Computer Repair',
      'PC Maintenance',
      'Networking',
      'Assembly',
    ],
  },
  {
    id: 23,
    slug: 'learn-ai',
    name: 'Learn AI',
    logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=300&fit=crop&crop=center&q=75',
    description:
      'Master Artificial Intelligence and Machine Learning. Learn to build AI models, work with Generative AI tools, and understand the future of technology.',
    overview:
      'Welcome to the future of technology with our "Learn AI" course at Gyanplanet Institute. Designed for beginners and professionals, this course demystifies Artificial Intelligence and its transformative impact across industries. You will explore core AI and Machine Learning concepts, understanding how neural networks learn from data. A significant highlight is our module on Generative AI, where you will master the art of Prompt Engineering to 10x your productivity. Learn to craft precise instructions for tools like ChatGPT and Gemini to automate tasks and generate high-quality content instantly. Beyond technical skills, we address AI ethics and practical implementation workflows. By the end of this intensive program, you will be equipped to leverage state-of-the-art AI tools to stay ahead in the rapidly evolving digital world.',
    benefits: [
      'Understand AI and ML fundamentals',
      'Master Prompt Engineering',
      'Build AI-powered workflows',
      'Explore Generative AI tools',
      'Stay ahead in the evolving tech landscape',
    ],
    whoShouldEnroll:
      'Students, Developers, Business Leaders, and anyone curious about the future of technology.',
    duration: '1 months',
    fee: '₹6,000',
    monthlyFee: '₹6,000',
    features: [
      'Machine Learning',
      'Neural Networks',
      'Generative AI',
      'AI Ethics',
    ],
    syllabus: [
      {
        module: 'AI Fundamentals',
        topics: [
          'History of AI',
          'Types of Machine Learning',
          'Neural Network Basics',
        ],
      },
      {
        module: 'Generative AI',
        topics: [
          'LLMs & Transformers',
          'Prompt Engineering',
          'ChatGPT & Gemini Mastery',
        ],
      },
      {
        module: 'Practical AI Tools',
        topics: [
          'Midjourney/DALL-E Basics',
          'AI for Productivity',
          'Automation with AI',
        ],
      },
    ],
    careerOpportunities: [
      'AI Prompt Engineer',
      'AI Implementation Consultant',
      'Data Science Associate',
      'Automation Specialist',
    ],
    resources: {
      free: ['DeepLearning.AI Courses', 'Microsoft AI for Beginners'],
      paid: ['ChatGPT Plus Subscription', 'Coursera AI Certifications'],
      online: ['Hugging Face Hub', 'Google Colab'],
      offline: ['AI Ethics Workshops'],
    },
    installationGuide:
      '1. Access tools like ChatGPT and Gemini online.\n2. For coding, set up Python and Jupyter Notebooks.\n3. Explore open-source models on Hugging Face.',
    alternatives: [
      { name: 'Claude.ai', link: 'https://claude.ai/' },
      { name: 'Perplexity AI', link: 'https://www.perplexity.ai/' },
    ],
    category: ['AI'],
    searchKeys: [
      'AI',
      'Artificial Intelligence',
      'Machine Learning',
      'Generative AI',
      'Deep Learning',
      'Neural Networks',
    ],
  },
];
